#!/bin/sh

# Increase key speed via a rate change
xset r rate 300 50
# Map the caps lock key to super...
#setxkbmap -layout us -variant altgr-intl -option caps:super
# If you don't want a us international keyboard, rather whatever keyboard
# you set in your installation, comment out the above line and uncomment
# the one below.
setxkbmap -option ctrl:nocaps


spare_modifier="Hyper_L"
target_key="Return"
target_code=36
xmodmap -e "keycode $target_code = $spare_modifier"  # Make 36(Return) Hyper_L
xmodmap -e "remove mod4 = $spare_modifier"  # Remove the default function of Hyper_L
# hyper_l is mod4 by default
xmodmap -e "add Control = $spare_modifier"  # Make Hyper_L(Now return) into Control

xmodmap -e "keycode any = $target_key"  # Add this key to empty place, assign no physical key to it


# Space to mod4 key

spare_modifier2="ISO_Level3_Shift"
spare_modifier2_sym="mod5"
xmodmap -e "keycode 65 = $spare_modifier2"
xmodmap -e "remove $spare_modifier2_sym = $spare_modifier2"
xmodmap -e "add mod4 = $spare_modifier2"

#Next, map space to an unused keycode (to keep it around for xcape to use).

xmodmap -e "keycode any = space"  # Add this key to empty place, assign no physical key to it


killall xcape; xcape -e "Shift_L=Shift_R|minus;Shift_R=minus;Control_L=Escape;$spare_modifier=$target_key;$spare_modifier2=space"  # second last Hyper_L = Return


# Remove redundant keys
#xmodmap -e 'remove control = Control_L'  # These two lines remove Capslock control too, so bad
#xmodmap -e 'add mod5 = Control_L'

# Reuse redundant keys
#xmodmap -e "remove Control = Control_L"
#xmodmap -e "remove Control = Control_R"
#xmodmap -e "keycode 37 = plus"  # Disable or reuse left control key, control key stays
#xmodmap -e "keycode 105 = space"  # Disable or reuse right control key, control key stays
